# Generated by Django 3.2.6 on 2021-08-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formula_one', '0002_alter_team_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userleague',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='formula_one.league'),
        ),
        migrations.AlterField(
            model_name='userleague',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
    ]
