# Generated by Django 3.2.6 on 2021-08-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_one', '0002_alter_driver_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='team',
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='drivers', through='formula_one.TeamDriver', to='formula_one.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_teams', to='formula_one.league'),
        ),
    ]
