# Generated by Django 3.2.6 on 2021-08-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_one', '0003_auto_20210816_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='drivers',
        ),
        migrations.AddField(
            model_name='team',
            name='drivers',
            field=models.ManyToManyField(blank=True, null=True, to='formula_one.Driver'),
        ),
    ]
