# Generated by Django 3.2.6 on 2021-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_one', '0004_auto_20210816_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='formula_one.Driver'),
        ),
    ]
